[package]
name = "spacemapd"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Spacemap background scanner daemon"

[dependencies]
spacemap-core.workspace = true
anyhow.workspace = true
clap.workspace = true
ctrlc.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
